version: '3'
services:
  traefik:
    image: traefik:v1.7.14-alpine
    container_name: traefik
    command: --api
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.toml:/traefik.toml
      - ./logs:/var/log/traefik
    networks:
      web:
        ipv4_address: 172.25.1.2
    labels:
      traefik.enable: true
      traefik.frontend.port: 8080
      traefik.frontend.rule: "Host:traefik.pzlocal.localhost"
      traefik.frontend.auth.basic.users: "trfkdmn:$$apr1$$vnNQ1MQD$$MhUaAreW1F.FwZ.x7bg.q0"

networks:
  web:
    external: true